/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gh;

/**
 *
 * @author Игорь
 */
public class ClientJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientJFrame
     */
    public ClientJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        main = new javax.swing.JPanel();
        guaranteesLabel = new javax.swing.JTextArea();
        tonAuto = new javax.swing.JLabel();
        expertMechanicsLabel = new javax.swing.JTextArea();
        marketYearsLabel = new javax.swing.JTextArea();
        request = new javax.swing.JPanel();
        order = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        guaranteesLabel.setEditable(false);
        guaranteesLabel.setColumns(20);
        guaranteesLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        guaranteesLabel.setRows(5);
        guaranteesLabel.setText("ГАРАНТИЯ НА РЕМОНТ\nИ ЗАПЧАСТИ\n\nНа выполненные работы и запчасти мы \nпредоставляем гарантию до 1 года.");
        guaranteesLabel.setAutoscrolls(false);
        guaranteesLabel.setMargin(new java.awt.Insets(3, 10, 3, 10));

        tonAuto.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        tonAuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tonAuto.setText("TonAuto");
        tonAuto.setBorder(new javax.swing.border.MatteBorder(null));
        tonAuto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        expertMechanicsLabel.setEditable(false);
        expertMechanicsLabel.setColumns(20);
        expertMechanicsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        expertMechanicsLabel.setRows(5);
        expertMechanicsLabel.setText("ОПЫТНЫЕ МАСТЕРА\n\nРегулярное повышение квалификации, \nобучение и современное оборудование \nпозволяют нам обеспечить высокое \nкачество исполнения любых работ по \nремонту автомобиля.");
        expertMechanicsLabel.setMargin(new java.awt.Insets(3, 10, 3, 10));

        marketYearsLabel.setEditable(false);
        marketYearsLabel.setColumns(20);
        marketYearsLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        marketYearsLabel.setRows(5);
        marketYearsLabel.setText("24 ГОДА НА РЫНКЕ\n\nЗа такой срок мы накопили огромный\nопыт в ремонте и обслуживании ино-\nмарок, автомобилей отечественного \nпроизводства и микроавтобусов.");
        marketYearsLabel.setAutoscrolls(false);
        marketYearsLabel.setMargin(new java.awt.Insets(3, 10, 3, 10));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(marketYearsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guaranteesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tonAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expertMechanicsLabel))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tonAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marketYearsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guaranteesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expertMechanicsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        jTabbedPane1.addTab("Главная", main);

        javax.swing.GroupLayout requestLayout = new javax.swing.GroupLayout(request);
        request.setLayout(requestLayout);
        requestLayout.setHorizontalGroup(
            requestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        requestLayout.setVerticalGroup(
            requestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Оставить заявку", request);

        javax.swing.GroupLayout orderLayout = new javax.swing.GroupLayout(order);
        order.setLayout(orderLayout);
        orderLayout.setHorizontalGroup(
            orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        orderLayout.setVerticalGroup(
            orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ваш заказ", order);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea expertMechanicsLabel;
    private javax.swing.JTextArea guaranteesLabel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel main;
    private javax.swing.JTextArea marketYearsLabel;
    private javax.swing.JPanel order;
    private javax.swing.JPanel request;
    private javax.swing.JLabel tonAuto;
    // End of variables declaration//GEN-END:variables
}
